baseURL = "http://localhost/"
languageCode = "en-us"
title = "LinuxBoot"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsUseClassic = true

[Params]
  useChroma = true
	subtitle = "Let Linux do it"
	logo = "images/logo.png"
	favicon = "images/favicon.ico"
	dateFormat = "January 2, 2006"
	commit = false
	rss = false
	comments = true
	readingTime = true

[Author]
	name = "The LinuxBoot project"
	website = "https://www.linuxboot.org"
	email = "linuxboot@googlegroups.com"
	github = "linuxboot"

[[menu.main]]
	name = "FAQ"
	url = "page/faq/"
	weight = 1

[[menu.main]]
	name = "About Us"
	url = "page/about/"
	weight = 2

[[menu.main]]
	name = "Artwork"
	url = "page/artwork/"
	weight = 3
