baseURL = "https://linuxboot.org/"
languageCode = "en-us"
title = "LinuxBoot"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsUseClassic = true

[Params]
  useChroma = true
	subtitle = ""
	logo = "images/logo.png"
	favicon = "images/favicon.ico"
	dateFormat = "January 2, 2006"
	commit = false
	rss = false
	comments = true

[Author]
	name = "The LinuxBoot project"
	website = "www.linuxboot.org"
	email = "linuxboot@googlegroups.com"
	github = "linuxboot"

[[menu.main]]
	name = "About"
	url = "page/about/"
	weight = 1
